### ISSUE TITLE
Content negotiation: Multiple accept mime types are not parsed correctly

### ISSUE THREAD

**Issue by MazeChaZer** [creios/creiwork-framework#17]
HTTPie default `Accept` header:
```
Accept: application/json, */*
```
Using this header, HTML will be returned. Instead it should be JSON.

**Comment by timtegeler** [comment]
Is this a showstopper or do you have a workaround? If this is urgent I could solve this later this day.

**Comment by MazeChaZer** [comment]
No, it's not urgent, just a little inconvenient using HTTPie. We can look at this later.

**Comment by timtegeler** [comment]
Ok. I looked at this already. At this moment I think either I am using the negotiation library the wrong way or the negotiation library has an bug.

**Comment by timtegeler** [comment]
I tried a little bit printf debugging with the negotiation library:

- If you are using the relative quality parameter `Accept:"application/json;q=1, */*;q=0.9"` it works like expected.

- If you not using the relative quality parameter like in your example `Accept: application/json, */*` the negotiation library matches application/json to json and */* to html. Both have a relative quality parameter of 1, because no relative quality parameter is set. Then the library tries to compare these matches by the relative quality parameter. Because both have the same relative quality parameter it uses the numeric array index of json and html. Because the index of html is lesser than the one from json, html wins. So I think the library does not factor in that that application/json is the more specific Content-Type and text/html is only a default value of */*.

**Comment by benjaminknauer** [comment]
removed the lib
